import Link from 'next/link';
import { Sparkles } from 'lucide-react';

export const metadata = {
  title: 'Privacy Policy — CandidAI',
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-200">
      <nav className="border-b border-slate-800">
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <Sparkles className="w-6 h-6 text-purple-500" />
            <span className="text-lg font-bold gradient-text">CandidAI</span>
          </Link>
          <span className="text-slate-400 text-sm">Privacy Policy</span>
        </div>
      </nav>

      <main className="max-w-3xl mx-auto px-6 py-12 space-y-10">
        <div>
          <h1 className="text-3xl font-bold mb-2">Privacy Policy</h1>
          <p className="text-slate-400 text-sm">Last updated: June 2025</p>
        </div>

        <Section title="Who we are">
          <p>CandidAI is operated by Aravind Praveen, an individual based in India. If you have any privacy-related questions, contact us at <a href="mailto:atomeo.019@gmail.com" className="text-purple-400 hover:underline">atomeo.019@gmail.com</a>.</p>
        </Section>

        <Section title="What we collect">
          <ul className="list-disc list-inside space-y-2 text-slate-300">
            <li><strong className="text-white">Account data</strong> — when you sign in with Google via Clerk, we receive your name and email address.</li>
            <li><strong className="text-white">Usage data</strong> — how many resumes you have analyzed (a count, never the content).</li>
            <li><strong className="text-white">Analysis scores</strong> — the numeric scores, tier, and feedback text generated by our AI. We store these so you can review past results.</li>
            <li><strong className="text-white">Payment data</strong> — if you purchase, Whop processes your payment. We only store a record that a purchase occurred (no card numbers, ever).</li>
          </ul>
        </Section>

        <Section title="What we do NOT collect">
          <div className="bg-green-500/10 border border-green-500/20 rounded-xl px-5 py-4">
            <p className="text-green-300 font-semibold mb-2">We never store your resume text.</p>
            <p className="text-slate-300 text-sm">When you upload a PDF, we extract the text, send it to our AI for analysis, and immediately discard it. The raw resume text is never written to a database, file system, or log. See our <Link href="/upload-disclosure" className="text-purple-400 hover:underline">Upload Disclosure</Link> for the full technical breakdown.</p>
          </div>
        </Section>

        <Section title="How we use your data">
          <ul className="list-disc list-inside space-y-2 text-slate-300">
            <li>To authenticate you and maintain your account.</li>
            <li>To enforce usage limits (free tier vs. paid).</li>
            <li>To show you your past analysis results.</li>
            <li>To deliver the cover letter feature to paid users.</li>
            <li>We do <strong className="text-white">not</strong> sell your data. We do not use it for advertising. We do not share it with third parties except the processors listed below.</li>
          </ul>
        </Section>

        <Section title="Third-party processors">
          <ul className="list-disc list-inside space-y-2 text-slate-300">
            <li><strong className="text-white">Clerk</strong> — authentication. <a href="https://clerk.com/privacy" className="text-purple-400 hover:underline" target="_blank" rel="noopener noreferrer">Privacy policy</a></li>
            <li><strong className="text-white">Neon</strong> — database hosting (your account data and analysis scores). <a href="https://neon.tech/privacy" className="text-purple-400 hover:underline" target="_blank" rel="noopener noreferrer">Privacy policy</a></li>
            <li><strong className="text-white">Groq</strong> — AI inference. Resume text is sent to Groq for analysis and is governed by their <a href="https://groq.com/privacy-policy/" className="text-purple-400 hover:underline" target="_blank" rel="noopener noreferrer">privacy policy</a>. We do not instruct Groq to retain your data.</li>
            <li><strong className="text-white">Whop</strong> — payment processing. <a href="https://whop.com/privacy" className="text-purple-400 hover:underline" target="_blank" rel="noopener noreferrer">Privacy policy</a></li>
          </ul>
        </Section>

        <Section title="Data retention">
          <p>Your account and analysis scores are retained as long as your account exists. You can request deletion at any time by emailing <a href="mailto:atomeo.019@gmail.com" className="text-purple-400 hover:underline">atomeo.019@gmail.com</a>. We will delete your data within 30 days.</p>
        </Section>

        <Section title="Your rights">
          <p>You have the right to access, correct, or delete your personal data. Email us and we will respond within 30 days. If you are in the EU/UK, you also have the right to lodge a complaint with your local data protection authority.</p>
        </Section>

        <Section title="Changes to this policy">
          <p>We may update this policy. If changes are material, we will update the date at the top of this page. Continued use of CandidAI after changes constitutes acceptance.</p>
        </Section>
      </main>

      <footer className="border-t border-slate-800 mt-12 py-6">
        <div className="max-w-3xl mx-auto px-6 flex gap-6 text-sm text-slate-500">
          <Link href="/privacy" className="hover:text-slate-300 transition-colors">Privacy</Link>
          <Link href="/terms" className="hover:text-slate-300 transition-colors">Terms</Link>
          <Link href="/cookie-policy" className="hover:text-slate-300 transition-colors">Cookies</Link>
          <Link href="/refund-policy" className="hover:text-slate-300 transition-colors">Refunds</Link>
          <Link href="/ai-disclaimer" className="hover:text-slate-300 transition-colors">AI Disclaimer</Link>
          <Link href="/upload-disclosure" className="hover:text-slate-300 transition-colors">Upload Disclosure</Link>
        </div>
      </footer>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="text-xl font-semibold text-white">{title}</h2>
      <div className="text-slate-300 leading-relaxed text-sm space-y-2">{children}</div>
    </section>
  );
}
