import Link from 'next/link';
import { LegalShell, LegalSection, LegalCallout, legalLink } from '@/components/brand/LegalShell';

export const metadata = {
  title: 'Privacy Policy — CandidAI',
};

export default function PrivacyPage() {
  return (
    <LegalShell label="Privacy Policy" title="Privacy Policy" subtitle="Last updated: June 2025">
      <LegalSection title="Who we are">
        <p>CandidAI is operated by Aravind Praveen, an individual based in India. If you have any privacy-related questions, contact us at <a href="mailto:atomeo.019@gmail.com" className={legalLink}>atomeo.019@gmail.com</a>.</p>
      </LegalSection>

      <LegalSection title="What we collect">
        <ul className="list-disc list-inside space-y-2">
          <li><strong className="text-foreground">Account data</strong> — when you sign in with Google via Clerk, we receive your name and email address.</li>
          <li><strong className="text-foreground">Usage data</strong> — how many resumes you have analyzed (a count, never the content).</li>
          <li><strong className="text-foreground">Analysis scores</strong> — the numeric scores, tier, and feedback text generated by our AI. We store these so you can review past results.</li>
          <li><strong className="text-foreground">Payment data</strong> — if you purchase, Whop processes your payment. We only store a record that a purchase occurred (no card numbers, ever).</li>
        </ul>
      </LegalSection>

      <LegalSection title="What we do NOT collect">
        <LegalCallout tone="confirm" title="We never store your resume text.">
          <p>When you upload a PDF, we extract the text, send it to our AI for analysis, and immediately discard it. The raw resume text is never written to a database, file system, or log. See our <Link href="/upload-disclosure" className={legalLink}>Upload Disclosure</Link> for the full technical breakdown.</p>
        </LegalCallout>
      </LegalSection>

      <LegalSection title="How we use your data">
        <ul className="list-disc list-inside space-y-2">
          <li>To authenticate you and maintain your account.</li>
          <li>To enforce usage limits (free tier vs. paid).</li>
          <li>To show you your past analysis results.</li>
          <li>To deliver the cover letter feature to paid users.</li>
          <li>We do <strong className="text-foreground">not</strong> sell your data. We do not use it for advertising. We do not share it with third parties except the processors listed below.</li>
        </ul>
      </LegalSection>

      <LegalSection title="Third-party processors">
        <ul className="list-disc list-inside space-y-2">
          <li><strong className="text-foreground">Clerk</strong> — authentication. <a href="https://clerk.com/privacy" className={legalLink} target="_blank" rel="noopener noreferrer">Privacy policy</a></li>
          <li><strong className="text-foreground">Neon</strong> — database hosting (your account data and analysis scores). <a href="https://neon.tech/privacy" className={legalLink} target="_blank" rel="noopener noreferrer">Privacy policy</a></li>
          <li><strong className="text-foreground">Groq</strong> — AI inference. Resume text is sent to Groq for analysis and is governed by their <a href="https://groq.com/privacy-policy/" className={legalLink} target="_blank" rel="noopener noreferrer">privacy policy</a>. We do not instruct Groq to retain your data.</li>
          <li><strong className="text-foreground">Whop</strong> — payment processing. <a href="https://whop.com/privacy" className={legalLink} target="_blank" rel="noopener noreferrer">Privacy policy</a></li>
        </ul>
      </LegalSection>

      <LegalSection title="Data retention">
        <p>Your account and analysis scores are retained as long as your account exists. You can erase your stored analyses yourself at any time using <strong className="text-foreground">Delete my data</strong> on your dashboard — that takes effect immediately. You can also email <a href="mailto:atomeo.019@gmail.com" className={legalLink}>atomeo.019@gmail.com</a> and we will delete your data within 30 days.</p>
      </LegalSection>

      <LegalSection title="Your rights">
        <p>You have the right to access, correct, or delete your personal data. Email us and we will respond within 30 days. If you are in the EU/UK, you also have the right to lodge a complaint with your local data protection authority.</p>
      </LegalSection>

      <LegalSection title="Changes to this policy">
        <p>We may update this policy. If changes are material, we will update the date at the top of this page. Continued use of CandidAI after changes constitutes acceptance.</p>
      </LegalSection>
    </LegalShell>
  );
}
